
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://bgoldman.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /

# Google tracking id to track your visitors

google-tracking-id: "UA-74071476-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Brandon Goldman"
title: "Brandon Goldman"
description: "Personal website of Brandon Goldman, tech enthusiast extraordinaire."
keywords: "brandon, goldman, personal, jekyll, theme"
favicon: "/img/favicon.png"
404-img: "/img/404.jpg"

################
# Header layout #
################

black-favicon: "/img/favicon-white.png"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
delete-speed: 2
start-delay: 200
delete-delay: 2000
lines: # You can add HTML Tags in the Text
  - text: "Welcome to the best Brandon Goldman site on the internet."
  - text: "My nephew calls me Uncie Bitcoin.^500<br />You can call me Brandon."
  - text: "Keep staring at the screen.^500<br />These are funny.^500<br />At least my wife told me they were."
  - text: 'One time a waiter at a fancy restaurant told me,^500<br />\"Sir, it is my job to know what vegan is\",^500<br />and then proceeded to serve me food that was not vegan.'
  - text: "Bananas are actually a type of berry, and banana trees aren't trees, but the world's largest herb.^500<br />Did anybody else know this?"
  - text: "What is the definition of salad?^500<br />What makes a food dish a salad or not a salad?"
  - text: "One time on a road trip, the bottom of a bag of food fell out and got everywhere in the car.^500<br />My wife and I had our dog eat it.^500<br />Now that's what I call a win-win situation.^500<br />Good dog, Buddy."
  - text: "Pro-tip: Always get BBQ sauce with fries.^500<br />Way better than ketchup."
  - text: "If I ever open a pizza restaurant, I'm going to call it Elemeno Pizza.^500<br />Please don't steal my idea."
  - text: "One time, I spent over an hour shopping on Amazon.com^500<br />...for the best toilet paper.^500<br />Was it worth it?^500<br />Yes."
  - text: "My wife makes the best BBQ tofu ever.^500<br />You should try it sometime."
  - text: "The only thing that could make that dessert better is pineapple."
  - text: "One time, my wife and I were visiting family in a small town in Colorado, and on the drive there, we were joking that they'd probably want to eat dinner at Cracker Barrel that evening.^500<br />A couple hours later, we were eating dinner at Cracker Barrel."
  - text: "Is a hot dog a sandwich?"
  - text: "Have you ever eaten at Chipotle, and while your burrito was being made, it accidentally exploded?^500<br />And then they tried to put the ingredients that fell in another tortilla?^500<br />I had that happen.^500<br />I paid extra for that guacamole, and now it's stuck to the inside of a tortilla in the trash."
  - text: "One time, I posted a homemade cat video on Facebook.^500<br />Looking back on it, I have no regrets."
  - text: "Challenge: Name a cracker that is better than a Triscuit."
  - text: "Fettuccine Alfredo is just Mac and Cheese for adults."
  - text: "One time, my wife and I started a short-lived catering company that specialized in vegan jackfruit tacos.^500<br />They were really good."
  - text: "Okay, last one.^500<br />Promise."
  - text: "One time, I engaged no less than thirty people on Facebook in a lively discussion about what the definition of a salad is.^500<br />I consider this to be a great success."
  - text: "My cat likes drinking Soylent, the liquid diet for busy professionals.^500<br />Does this mean my cat is a busy professional?"
  - text: "I think it would be fair to call me a taco enthusiast."
  - text: "Wanted: Somebody to go back in time with me.^500<br />This is not a joke.^500<br />You'll get paid after we get back.^500<br />Must bring your own weapons.^500<br />Safety not guaranteed.^500<br />I have only done this once before."
  - text: "All your base^500 are belong to us."
  - text: "I don't need to fight.^500<br />To proooooooooove I'm right.^500<br />I don't neeeeeeeeeed to be for^500giv^500en.^500<br />Yeah, yeah, yeah, yeah,^500 yeah^500-ah."
  - text: "Fact: broccoli, brussels sprouts, cabbage, cauliflower, collard greens, and kale - believe it or not - are all just different versions of the same plant."
  - text: "One day, I'm going to fly to the moon.^500<br />I just need to wait until I have an extra five million dollars,^500<br />and for the technology to be reinvented and mass marketed.^500<br />So like next year, maybe the year after?"
  - text: "How about that Hyperloop?^500<br />Are you looking forward to it?^500<br />I'm looking forward to it."
  - text: "Hopefully my next car will be a Tesla.^500<br />I'm holding out for the one that regular people can afford to buy."
  - text: "These things load in a random order.^500<br />But once you see the same one twice it means they're repeating.^500<br />You can stop after that."
  - text: "Sometimes I have a conversation with my cat.^500<br />No, really.^500 I'm serious.^500<br />Like, he'll walk up and meow and then I'll respond with a meow and then he meows back and we just kind of keep going until one of us stops.^500<br />It's pretty awesome.^500 Don't judge me."
  - text: "You want the truth?^500<br />You can't handle the truth!^<br />Okay fine, I'll tell you the truth.^<br />I ate the last cookie.^500 I was really hungry.^500 I'm sorry."
  - text: "I only wear toe socks.^500<br />You know, the kind that fit around each toe separately.^500<br />I don't like the way regular socks feel on my feet.^500 These are way better.^500 You should buy some."
  - text: "Challenge. Eat eight kiwi fruits in one sitting.^500<br />I call this The Kiwi Challenge.^500<br />Do it.^500 I've done it once before."
  - text: "My dog Buddy likes yogurt.^500 I mean, he really likes yogurt.^500 A lot.^500<br />The funny thing is, he hasn't even had that much of it.^500<br />Just if yogurt comes out, there he is, more than other foods.^500<br />We let him lick the spoon."

me-img: "/img/me.png"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "begoldman"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/chester.jpg"
    date: "March 2015"
    description: "Welcome, Chester! Adopted the sweetest homeless cat off the street. One of friendliest cats we've ever met."
  - image: "/img/timeline/box-ipo.jpg"
    date: "January 2015"
    description: "Box had an IPO. Very lucky to have worked at a company that made it this far!"
  - image: "/img/timeline/san-francisco.jpg"
    date: "April 2014"
    description: "Moved back up to the SF Bay Area! I wanted to move my company here, and Sherri got a job at Google!"
  - image: "/img/timeline/freshpay.png"
    date: "June 2013 - Present"
    description: "Started my company FreshPay, in the cryptocurrency space."
  - image: "/img/timeline/bitcoin.jpg"
    date: "April 2013"
    description: "I bought my first bitcoin."
  - image: "/img/timeline/buddy.jpg"
    date: "August 2012"
    description: "Yay, we got a dog! We adopted Buddy from a rescue. He's basically the best dog ever."
  - image: "/img/timeline/andalucia.jpg"
    date: "May 2012"
    description: "We bought our first house! Redondo Beach, California."
  - image: "/img/timeline/wedding.jpg"
    date: "July 2011"
    description: "Got married to my wonderful wife, Sherri."
  - image: "/img/timeline/miso-media.jpg"
    date: "June 2011 - July 2012"
    description: "Joined Miso Media as VP of Engineering."
  - image: "/img/timeline/long-beach.jpg"
    date: "January 2010"
    description: "Moved back down to LA to live in Long Beach with Sherri."
  - image: "/img/timeline/engagement.jpg"
    date: "January 2010"
    description: "Asked Sherri to marry me and she said yes :)"
  - image: "/img/timeline/goldman-interactive.png"
    date: "December 2008 - September 2013"
    description: "Started a software consulting company. Mostly a one-man show. Worked on the neighborhood of a hundred projects."
  - image: "/img/timeline/box.gif"
    date: "October 2007 - December 2008"
    description: "Joined as one of the first dozen employees at a then-small startup."
  - image: "/img/timeline/palo-alto.png"
    date: "October 2007"
    description: "Moved up to the SF Bay Area."
  - image: "/img/timeline/parcel-pro.png"
    date: "January 2007 - September 2007"
    description: "Took a new job as a senior web developer at a shipping and insurance startup for the jewelry industry."
  - image: "/img/timeline/met-sherri.jpg"
    date: "May 2006"
    description: "Met Sherri - little did I know, she would become my wife later on."
  - image: "/img/timeline/itvn.png"
    date: "May 2006 - January 2007"
    description: "Got my first full-time job at a tech startup, as a software developer at one of the first IPTV companies, with a real salary and everything."
  - image: "/img/timeline/dropout.png"
    date: "March 2006"
    description: "Became a degenerate and dropped out of college."
  - image: "/img/timeline/ucr.jpg"
    date: "September 2004"
    description: "Went to college."
  - image: "/img/timeline/matrix.jpg"
    date: "2002"
    description: "Started doing real programming."
  - image: "/img/timeline/html.png"
    date: "1997"
    description: "Started coding, but mostly HTML."
  - image: "/img/timeline/little-kid.jpg"
    date: "June 1986"
    description: "I was born. I have a twin brother. Guess which one is me?"

# First image of the Timeline

timeline-img: "/img/me.png"

###########
# Contact #
###########

email: "brandon.goldman@gmail.com"

################
# Author Blurb #
################

author_blurb: "Brandon Goldman is a vegan, libertarian, college dropout, entrepreneur, and software engineer from California, where he works on his company FreshPay and also does freelance software development work for Gigster. He lives in the SF Bay Area with his wife Sherri, who is a systems engineer at Google on Project Loon. They live with a dog named Buddy and a cat named Chester. In his spare time, Brandon is a self-proclaimed taco enthusiast."
author_blurb_image: "/img/me-real.jpg"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/begoldman"
  - title: "github"
    url: "https://github.com/bgoldman"
  - title: "linkedin"
    url: "https://linkedin.com/in/bgoldman"
  - title: "angellist"
    url: "https://angel.co/begoldman"
  - title: "twitter"
    url: "https://twitter.com/bgoldman86"
  - title: "bitcoin"
    url: "https://coinbase.com/bgoldman"
  - title: "rss"
    url: "/feed.xml"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
