
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "http://www.brandongoldman.com"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id to track your visitors

google-tracking-id: "UA-74071476-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

#############
# HTML Head #
#############

lang: "en"
author: "Brandon Goldman"
title: "Brandon Goldman"
description: "Personal website of Brandon Goldman."
keywords: "brandon, goldman, personal, jekyll, theme"
favicon: "/img/favicon.png"
404-img: "/img/404.jpg"

################
# Header layout #
################

black-favicon: "/img/favicon-white.png"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
delete-speed: -20
start-delay: 500
delete-delay: 2000
line2:
# Me
  - text: "Welcome to the best Brandon Goldman site on the internet."
  - text: "My nephew calls me Uncie Bitcoin.^500<br />You can call me Brandon."
  - text: "My brother's name is Brent and my dad's name is Bob.^500<br />Our initials are all the same.^500 Maybe we could start a pop music band called the Bee Gees.^500 <br />What?^500 That's already been done?"

# Protips
  - text: "Protip:^500 Always get BBQ sauce with fries.^500<br />Way better than ketchup."

# Hope
  - text: "One day, I'm going to fly to the moon.^500<br />I just need to wait until I have an extra five million dollars,^500<br />and for the technology to be reinvented and mass marketed.^500<br />So like next year, maybe the year after?"
  - text: "Hopefully my next car will be a Tesla.^500<br />I'm holding out for the one that regular people can afford to buy."

# Fun Facts
  - text: "I only wear toe socks.^500<br />You know, the kind that fit around each toe separately.^500<br />I don't like the way regular socks feel on my feet.^500 These are way better.^500 You should buy some."
  - text: "Sometimes I have a conversation with my cat.^500<br />No, really.^500 I'm serious.^500<br />Like, he'll walk up and meow and then I'll respond with a meow and then he meows back and we just kind of keep going until one of us stops.^500<br />It's pretty awesome.^500 Don't judge me."

# Bad Jokes
  - text: "Keep staring at the screen.^500<br />These are funny.^500<br />At least my wife told me they were."
  - text: "Okay,^500 last one.^500<br />Promise."
  - text: "These things load in a random order.^500<br />But once you see the same one twice it means they're repeating.^500<br />You can stop after that."
  - text: "I wrote a Haiku.^500<br />Okay, maybe I did^500n't.^500<br /> Wait,^1000 I think I did."

# Pop Culture
  - text: "I don't need to fight.^500<br />To proooooooooove I'm right.^500<br />I don't neeeeeeeeeed to be for^500giv^500en.^500<br />Yeah, yeah, yeah, yeah,^500 yeah^500-ah."
  - text: "Ain't got no distractions,^500 can't hear no buzzers and bells.^500<br />Don't see no lights a^100-flashin'^500, plays by sense of smell.^500<br />Always gets a replay,^500 never seen him fall.^500<br />That deaf, dumb, and blind kid,^500<br />sure plays a mean pin^150ball."
  - text: "You want the truth?^500<br />You can't handle the truth!^500<br />Okay fine,^500 I'll tell you the truth.^<br />I ate the last cookie.^500 I was really hungry.^500 I'm sorry."
  - text: "All your base^250 are^100 belong to^100 us."
  - text: "Wanted:^500 Somebody to go back in time with me.^500<br />This is not a joke.^500 You'll get paid after we get back.^500<br />Must bring your own weapons.^500 Safety not guaranteed.^500<br />I have only done this once before."
  - text: "There’s always money in the banana stand."
  - text: "...and that's why,^250 you^150 always^150 leave^150 a^150 note."
  - text: "Winter is coming."

# One Time
  - text: "One time I went to the airport and told them I lost my driver license,^500 even though I didn't,^500 just to see what would happen.^500<br />I was still able to board my flight, but the inconvenience wasn't worth the extra time."
  - text: "One time I went vegan cold turkey.^500<br />Literally cold turkey^500 - my last meal as an omnivore was a^250 turkey^250 sandwich.^500<br />Almost a decade later,^500 still vegan."
  - text: 'One time a waiter at a fancy restaurant told me,^500<br />\"Sir,^250 it is my job to know what vegan is\",^500<br />and then proceeded to serve me food that was not vegan.'
  - text: "One time on a road trip, the bottom of a bag of food fell out and the food got everywhere in the car.^500<br />My wife and I had our dog eat it.^500<br />Now that's what I call a win-win situation.^500<br />Good dog, Buddy."
  - text: "One time, I engaged no less than thirty people on Facebook in a lively discussion about what the definition of a salad is.^500<br />I consider this to be a great success."
  - text: "One time, my wife and I started a short-lived catering company that specialized in vegan jackfruit tacos.^500<br />They were really good."
  - text: "One time, I posted a homemade cat video on Facebook.^500<br />Looking back on it,^500 I have no regrets."
  - text: "One time, my wife and I were visiting family in a small town in Colorado, and on the drive there, we were joking that they'd probably want to eat dinner at Cracker Barrel that evening.^500<br />A couple hours later, we were eating dinner at Cracker Barrel."
  - text: "One time, I spent over an hour shopping on Amazon.com^500<br />...for the best toilet paper.^500<br />Was it worth it?^500<br />Yes."

# Food
#  - text: "Fact:^500 Broccoli, broccolini, brussels sprouts, cabbage, cauliflower, collard greens, and kale, believe it or not, are all just different versions of the same plant."
  - text: "Fettuccine Alfredo is just Mac and Cheese for adults."
  - text: "My cat likes drinking Soylent, the liquid diet for busy professionals.^500<br />Does this mean my cat is a busy professional?"
  - text: "I think it would be fair to call me a vegan grilled cheese sandwich enthusiast."
  - text: "Challenge:^500 Eat eight kiwis in a row. The Kiwi Challenge.^500<br />Will something happen?^500 Will nothing happen?^500<br /> Eat eight kiwis to find out!^500 (I have done this once before)"
  - text: "My dog Buddy likes yogurt.^500 I mean,^250 he really likes yogurt.^500 A lot.^500<br />The funny thing is,^250 he hasn't even had that much of it.^500<br />Just if yogurt comes out,^250 there he is,^250 more than other foods.^500<br />We let him lick the spoon."
  - text: "I regularly eat four to six bananas per day."
  - text: "I know that avocados and tomatoes are technically fruits,^500 but come on,^500 everybody really knows they're vegetables."
  - text: "Bananas are actually a type of berry, and banana trees aren't trees, but the world's largest herb.^500<br />Did anybody else know this?"
  - text: "What is the definition of salad?^500<br />What makes a food dish a salad or not a salad?"
  - text: "If I ever open a pizza restaurant,^500 I'm going to call it Elemeno Pizza.^500<br />Please don't steal my idea."
  - text: "My wife makes the best BBQ tofu ever.^500<br />You should try it sometime."
  - text: "The only thing that could make that dessert better is pineapple."
  - text: "Is a hot dog a sandwich?"
  - text: "Have you ever eaten at Chipotle, and while your burrito was being made, it accidentally exploded?^500<br />And then they tried to put the ingredients that fell in another tortilla?^500<br />I had that happen.^500<br />I paid extra for that guacamole, and now it's stuck to the inside of a tortilla in the trash."
  - text: "Challenge:^500 Name a cracker that is better than a Triscuit."

me-img: "/img/me.png"

################
# Web App Mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "begoldman"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/chester.jpg"
    date: "March 2015"
    description: "Welcome, Chester! Adopted the sweetest homeless cat off the street. One of friendliest cats we've ever met."
  - image: "/img/timeline/box-ipo.jpg"
    date: "January 2015"
    description: "Box had an IPO. Very lucky to have worked at a company that made it this far!"
  - image: "/img/timeline/san-francisco.jpg"
    date: "April 2014"
    description: "Moved back up to the SF Bay Area! I wanted to move my company here, and Sherri got a job at Google!"
  - image: "/img/timeline/freshpay.png"
    date: "June 2013 - Present"
    description: "Started my company FreshPay, in the cryptocurrency space."
  - image: "/img/timeline/bitcoin.jpg"
    date: "April 2013"
    description: "I bought my first bitcoin."
  - image: "/img/timeline/buddy.jpg"
    date: "August 2012"
    description: "Yay, we got a dog! We adopted Buddy from a rescue. He's basically the best dog ever."
  - image: "/img/timeline/andalucia.jpg"
    date: "May 2012"
    description: "We bought our first house! Redondo Beach, California."
  - image: "/img/timeline/wedding.jpg"
    date: "July 2011"
    description: "Got married to my wonderful wife, Sherri."
  - image: "/img/timeline/miso-media.jpg"
    date: "June 2011 - July 2012"
    description: "Joined Miso Media as VP of Engineering."
  - image: "/img/timeline/long-beach.jpg"
    date: "January 2010"
    description: "Moved back down to LA to live in Long Beach with Sherri."
  - image: "/img/timeline/engagement.jpg"
    date: "January 2010"
    description: "Asked Sherri to marry me and she said yes :)"
  - image: "/img/timeline/goldman-interactive.png"
    date: "December 2008 - September 2013"
    description: "Started a software consulting company. Mostly a one-man show. Worked on the neighborhood of a hundred projects."
  - image: "/img/timeline/box.gif"
    date: "October 2007 - December 2008"
    description: "Joined as one of the first dozen employees at a then-small startup."
  - image: "/img/timeline/palo-alto.png"
    date: "October 2007"
    description: "Moved up to the SF Bay Area."
  - image: "/img/timeline/parcel-pro.png"
    date: "January 2007 - September 2007"
    description: "Took a new job as a senior web developer at a shipping and insurance startup for the jewelry industry."
  - image: "/img/timeline/met-sherri.jpg"
    date: "May 2006"
    description: "Met Sherri - little did I know, she would become my wife later on."
  - image: "/img/timeline/itvn.png"
    date: "May 2006 - January 2007"
    description: "Got my first full-time job at a tech startup, as a software developer at one of the first IPTV companies, with a real salary and everything."
  - image: "/img/timeline/dropout.png"
    date: "March 2006"
    description: "Became a degenerate and dropped out of college."
  - image: "/img/timeline/ucr.jpg"
    date: "September 2004"
    description: "Went to college."
  - image: "/img/timeline/matrix.jpg"
    date: "2002"
    description: "Started doing real programming."
  - image: "/img/timeline/html.png"
    date: "1997"
    description: "Started coding, but mostly HTML."
  - image: "/img/timeline/little-kid.jpg"
    date: "June 1986"
    description: "I was born. I have a twin brother. Guess which one is me?"

# First image of the Timeline

timeline-img: "/img/me.png"

###########
# Contact #
###########

email: "brandon.goldman@gmail.com"

################
# Author Blurb #
################

author_blurb: "Brandon Goldman is a vegan, libertarian, college dropout, entrepreneur, software engineer, and angel investor from California, where he works on his company FreshPay and also does freelance software development work for Gigster. He lives in the SF Bay Area with his wife Sherri, who is a systems engineer at Google on Project Loon. They live with a dog named Buddy and a cat named Chester. In his spare time, Brandon is a self-proclaimed vegan grilled cheese sandwich enthusiast."
author_blurb_image: "/img/me-real.jpg"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/begoldman"
  - title: "github"
    url: "https://github.com/bgoldman"
  - title: "linkedin"
    url: "https://linkedin.com/in/bgoldman"
  - title: "angellist"
    url: "https://angel.co/begoldman"
  - title: "twitter"
    url: "https://twitter.com/bgoldman86"
  - title: "bitcoin"
    url: "https://coinbase.com/bgoldman"
  - title: "rss"
    url: "/feed.xml"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
